import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Services",
  description: "Generated by create next app",
};

export default function ServicesPage() {
  return <></>;
}
