// SEO

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Amethyst Therapies - Accueil",
    template: "Amethyst Therapies - %s",
  },
  description: "Generated by create next app",
};

// FONT
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

// STYLES

import "./globals.css";

// COMPONENTS

import Header from "@/components/includes/header";
import Footer from "@/components/includes/footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
