import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Qui suis-je ?",
  description: "Generated by create next app",
};

export default function QuiSuisJePage() {
  return <></>;
}
